Improve Profile UX, redirect to Profile on signup
WarwickTabletop/tgrsite pull request #320
Opened 2022-02-20 18:31 UTC by finnbar

As title says - we now redirect to Profile on signup and make editing your profile really obvious.

2022-02-20 18:35 UTC, finnbar commented
This aims to complete #318.

2022-02-26 16:51 UTC, the-Bruce requested changes

2022-02-26 16:51 UTC, the-Bruce commented on users/templates/users/view.html
> +{% endblock %}
This should really be added to `tgrsite_local.scss` rather than inline

2022-02-26 16:51 UTC, the-Bruce commented on users/templates/users/view.html
> +{% endblock %}
(If you need me to do this to avoid setting up the compile toolchain, just let me know)

2022-02-26 17:34 UTC, the-Bruce approved these changes

2022-02-26 17:52 UTC, merged